config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  # resources :users, only: [:index, :destroy]
  
  resources :groups do 
    resources :payments_entities, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorisation.rb
class Categorisation < ApplicationRecord
  belongs_to :group
  belongs_to :payments_entity
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  has_and_belongs_to_many :groups
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :categorisations
  has_many :payments_entities, through: :categorisations
  attribute :icon, :string, default: 'image upload'
  has_one_attached :icon
  validates :name, :icon, presence: true
end

app/models/payments_entity.rb
class PaymentsEntity < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  has_many :categorisations
  has_many :groups, through: :categorisations
end

app/models/user.rb
class User < ApplicationRecord
  has_many :payments_entity, foreign_key: 'author_id'
  has_many :groups
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    attributes = [:name]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

  def after_sign_in_path_for(_resource)
    groups_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @currentuser = current_user.name
    @groups = current_user.groups
    @total = {}
    @groups.each do |group|
      @total[group] = group.payments_entities.sum(:amount)
    end
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user # Associate the current user with the group

    if @group.save
      @group.icon.attach(params[:group][:icon]) if params[:group][:icon].present?
      redirect_to groups_path, notice: 'Group was successfully created.'

    else
      render :new
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_payments
    @group = Group.find(params[:id])
    @payments_entities = @group.payments_entities
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/payments_entities_controller.rb
class PaymentsEntitiesController < ApplicationController
  before_action :set_group
  before_action :set_payments_entity, only: %i[show edit update destroy]

  def index
    @group = Group.find(params[:group_id])
    @payments_entities = @group.payments_entities.where(author_id: current_user.id).order(created_at: :desc)
    @total = @payments_entities.sum(:amount)
  end

  def new
    @group = Group.find(params[:group_id])
    @payments_entity = @group.payments_entities.build
  end

  def show
    @group = Group.find(params[:group_id])
    @payment = @group.payments_entities.build
  end

  def create
    @payment = @group.payments_entities.build(payments_entity_params)
    @payment.author_id = current_user.id

    if @payment.valid? && @payment.save
      Categorisation.create(payments_entity: @payment, group: @group)
      redirect_to group_payments_entities_path(@group), notice: 'Transaction added successfully.'
    else
      puts @payment.errors.full_messages
      render :new
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_payments_entity
    @payments_entity = PaymentsEntity.find(params[:id])
  end

  def payments_entity_params
    params.require(:payments_entity).permit(:name, :amount)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def index
      # Your code to fetch and prepare data goes here
      @users = User.all
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/entities/_form.html.erb
<%= form_with(model: entity) do |form| %>
  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.number_field :author_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :created_at, style: "display: block" %>
    <%= form.datetime_field :created_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_form.html.erb
<%= form_for(@group, url: groups_path, html: { multipart: true }) do |form| %>
  <nav class='flexer'>
  <a href='<%= groups_path %>' class='nav-link'>
          <svg xmlns="http://www.w3.org/2000/svg" class='back-arrow' fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
          </svg>
        </a>
        <h2 class='banner'>ADD</h2>
        <div>
      <%= form.submit 'Create entry', class: 'login-btn' %>
    </div>
  </nav>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.text_field :name, placeholder: "Name" %>
  </div>

  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.file_field :icon %>
  </div>

<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<nav class='flexer'>

      <h2 class='banner'>Categories</h2>
      <div>
<%= button_to 'Logout', destroy_user_session_path, method: :delete,class: 'login-btn' %>
      </div>
</nav>

<div class='hero'>
<p class = "welcome-note">Hello <%= @currentuser %>!<br>Below are your categories!</p>
</div>

<div class='overall-container'>
<% if @groups.empty? %>
  <p>No categories available. Add new categories</p>
<% else %>

<% @groups.each do |group| %>
    <div class="category-card">
      <%= link_to group_payments_entities_path(group),class:'a-tag blacker' do %>
        <div class="category-content flexer">
          <% if group.icon.present? %>
            <%= image_tag group.icon, alt: group.name, class: 'category-icon' %>
          <% else %>
            <%= image_tag 'placeholder-icon.png', alt: 'Placeholder Icon', class: 'category-icon' %>
          <% end %>

          <div class="category-details flexer">
            <h4 class="category-name"><%= group.name %></h4>
            <p class="category-amount">$<%= @total[group] %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

</div>

<div class='bottom-button sign-links'>
  <%= link_to 'ADD NEW CATEGORY', new_group_path, class: 'new-cart a-tag' %>
</div>

app/views/groups/new.html.erb
<%= render "form", group: @group %>

app/views/home/index.html.erb
<div class='logo-container'>
<h1>BillChum</h1>
</div>

<div class='sign-links flexer'>
<%= link_to 'LOG IN', new_user_session_path,class:'sign-up a-tag bluer'%>
<%= link_to 'SIGN UP', new_user_registration_path,class:'sign-up a-tag' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/payments_entities/_form.html.erb
<%= form_with(model: [@group, @payments_entity]) do |form| %>

  <nav class='flexer'>
<a href='<%= group_payments_entities_path(@group) %>' class='nav-link'>
        <svg xmlns="http://www.w3.org/2000/svg" class='back-arrow' fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
        </svg>
      </a>
      <h2 class='banner'>ADD</h2>
      <div>
    <%= form.submit 'Create Entry', class: 'login-btn' %>
  </div>
</nav>
  <% if payments_entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payments_entity.errors.count, "error") %> prohibited this payments_entity from being saved:</h2>

      <ul>
        <% payments_entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.text_field :name, placeholder: "Name"%>
  </div>

  <div class="field">
    <%= form.number_field :amount, placeholder: "Amount" %>
  </div>

<% end %>

app/views/payments_entities/_payments_entity.html.erb
<div id="<%= dom_id payments_entity %>">
  <p>
    <strong>Author:</strong>
    <%= payments_entity.author_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= payments_entity.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payments_entity.amount %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= payments_entity.created_at %>
  </p>

</div>

app/views/payments_entities/edit.html.erb
<h1>Editing payments_entities</h1>

<%= render "form", payments_entity: @payments_entity %>

<br>

<div>
  <%= link_to "Show this payments_entity", @payments_entity %> |
  <%= link_to "Back to payments_entities", payments_entities_path %>
</div>

app/views/payments_entities/index.html.erb
<nav class='flexer'>
<a href='<%= groups_path %>' class='nav-link'>
        <svg xmlns="http://www.w3.org/2000/svg" class='back-arrow' fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
        </svg>
      </a>
      <h2 class='banner'>TRANSACTIONS</h2>
      <div>
<%= button_to 'Logout', destroy_user_session_path, method: :delete,class: 'login-btn' %>
      </div>
</nav>
<div class='overall-container'>
<div class='hero'>
  <p>Total amount for this category: $ <%= @total %></p>
</div>

<%if @payments_entities.empty?%>
<p>No transactions add to this category</p>
<%else%> 
<% @payments_entities.each do |pe| %>
  <div class="category-card flexerier">
    <p><strong>Name:</strong> <%= pe.name %></p>
    <p><strong></strong>$<%= pe.amount %></p>
  </div>
<% end %> 
<% end %> 
<div class='bottom-button sign-links'> 
 <%= link_to 'Add New Transaction', new_group_payments_entity_path, class: 'new-cart a-tag' %>
</div>

app/views/payments_entities/new.html.erb
<%= render partial: 'form', locals: { group: @group, payments_entity: @payments_entity } %>

app/views/payments_entities/show.html.erb
<%= render @payments_entity %>

<div>
  <%= link_to "Edit this payments_entity", edit_payments_entity_path(@payments_entity) %> |
  <%= link_to "Back to payments_entities", payments_entities_path %>

  <%= button_to "Destroy this payments entity", @payments_entity, method: :delete %>
</div>